version: '3.5'
services:
  ldap-server:
    image: akhilrajmailbox/ldap-server:1.0.0
    # build:
    #   context: ./Docker
    #   dockerfile: Dockerfile
    container_name: ldap-server
    hostname: ldap-server
    restart: on-failure:5
    # env_file:
    #   - value.env
    environment:
      - LDAP_SERVER_NAME="My DevOps"
      - LDAP_ADMIN_PASS=SomeSecurePass
      - LDAP_DOMAIN=my.devops.example.com
      - LDAP_ORGANISATION=devops
      - HTPASSWORD=SomeSecurePass
      - ALIAS=devopssso
      - SSL_CONFIG=y
      - SSL_CERT=/usr/share/my-certs/example.crt
      - SSL_KEY=/usr/share/my-certs/example.key
      - SSL_CACERT=/usr/share/my-certs/example-bundle.crt
    ports:
      # - 30389:389
      # - 30080:80
      - 30636:636
      - 30443:443
    volumes:
      - /DATA/DevOps/ldap-server/apache2:/etc/apache2
      - /DATA/DevOps/ldap-server/phpldapadmin:/etc/phpldapadmin
      - /DATA/DevOps/ldap-server/ldap:/var/lib/ldap
      - /DATA/DevOps/ldap-server/ldapdb-backups:/var/backups
      - /DATA/DevOps/ldap-server/slapd.d:/etc/ldap/slapd.d
      - /DATA/DevOps/nginx-proxy/my-certs/:/usr/share/my-certs/:ro
    networks:
      - ldap-network

networks:
  ldap-network:
    external: true
    name: devops-network