# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.8'
services:
  ldap-server:
    image: akhilrajmailbox/ldap-server:lam-1.0.0
    environment:
      LDAP_DOMAIN: "devops.example.com"
      LDAP_ORGANISATION: "devops"
      # LDAP_SERVER_NAME: "My DevOps"
      # ALIAS: "devopssso"
      SSL_CONFIG: "y"
      HTPASSWORD_FILE: "/run/secrets/LDAP_HTPASSWORD_SECRET"
      LDAP_ADMIN_PASS_FILE: "/run/secrets/LDAP_ADMIN_PASS_SECRET"
      SSL_CERT: "/run/secrets/MY_SSL_CERT_SECRET"
      SSL_KEY: "/run/secrets/MY_SSL_KEY_SECRET"
      SSL_CACERT: "/run/secrets/MY_SSL_BUNDLE_SECRET"
    secrets:
      - LDAP_HTPASSWORD_SECRET
      - LDAP_ADMIN_PASS_SECRET
      - MY_SSL_CERT_SECRET
      - MY_SSL_KEY_SECRET
      - MY_SSL_BUNDLE_SECRET
    ports:
      - target: 636
        published: 636
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "https://localhost:443/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 120s
    labels:
      - "com.devops.service.name=ldap"
      - "com.devops.service.module=auth-provider"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "com.devops.service.name=ldap"
        - "com.devops.service.module=auth-provider"
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause # rollback
        monitor: 5s
        order: stop-first
      # rollback_config:
      #   parallelism: 1
      #   delay: 10s
      #   failure_action: pause
      #   monitor: 5s
      #   order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        # window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
          - "node.platform.os==linux"
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.100"
          memory: 0.5G
    volumes:
      # Directory must exist on the Host
      - /DevOps/ldap-server/apache2:/etc/apache2
      # phpldap
      # - /DevOps/ldap-server/phpldapadmin:/etc/phpldapadmin
      # lamldap
      - /DevOps/ldap-server/lib-ldap-account-manager:/var/lib/ldap-account-manager
      - /DevOps/ldap-server/etc-ldap-account-manager:/etc/ldap-account-manager
      - /DevOps/ldap-server/ldap:/var/lib/ldap
      - /DevOps/ldap-server/ldapdb-backups:/var/backups
      - /DevOps/ldap-server/slapd.d:/etc/ldap/slapd.d
    networks:
      - swarm-network

secrets:
  LDAP_HTPASSWORD_SECRET:
    external: true
  LDAP_ADMIN_PASS_SECRET:
    external: true
  MY_SSL_CERT_SECRET:
    external: true
  MY_SSL_KEY_SECRET:
    external: true
  MY_SSL_BUNDLE_SECRET:
    external: true

networks:
  swarm-network:
    external: true
    name: swarm-network